version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crud_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_db
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: crud_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build: ./api
    container_name: crud_api
    environment:
      - DATABASE_URL=mysql+pymysql://crud_user:crud_password@mysql:3306/crud_db
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api:/app
    restart: unless-stopped

  frontend:
    build: ./view
    container_name: crud_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./view:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mysql_data: