version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crud_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_db
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: crud_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api-go:
    build: ./api-go
    container_name: crud_api_go
    environment:
      - DATABASE_URL=crud_user:crud_password@tcp(mysql:3306)/crud_db?charset=utf8mb4&parseTime=True&loc=Local
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api-go:/app
    restart: unless-stopped

  frontend:
    build: ./view
    container_name: crud_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./view:/app
      - /app/node_modules
    depends_on:
      - api-go
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.71.0
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC endpoint
      - "6831:6831/udp" # Agent (optional)
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    restart: unless-stopped

volumes:
  mysql_data: 