version: '3.8'

services:
  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MCP_PORT=8080
      - DATABASE_URL=mysql://crud_user:crud_password@mysql:3306/crud_db?charset=utf8mb4&parseTime=True&loc=Local
      - DB_USER=crud_user
      - DB_PASSWORD=crud_password
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=crud_db
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Reference to existing MySQL service
  mysql:
    external: true 