include:
  - docker-compose.mysql.yml
  - docker-compose.frontend.yml

services:
  api-go:
    build: ./api-go
    container_name: crud_api_go
    environment:
      - DATABASE_URL=crud_user:crud_password@tcp(mysql:3306)/crud_db?charset=utf8mb4&parseTime=True&loc=Local
      - OTEL_EXPORTER_OTLP_ENDPOINT=jaeger:4317
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api-go:/app
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC endpoint
      - "6831:6831/udp" # Agent (optional)
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    restart: unless-stopped

  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    ports:
      - "9428:9428"
    volumes:
      - victorialogs-data:/victoria-logs-data
    restart: unless-stopped

  filebeat:
    image: elastic/filebeat:9.0.3
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    depends_on:
      - victorialogs
    restart: unless-stopped

volumes:
  victorialogs-data: 