include:
  - docker-compose.mysql.yml
  - docker-compose.frontend.yml
services:
  api:
    build: ./api
    container_name: crud_api
    environment:
      - DATABASE_URL=mysql+pymysql://crud_user:crud_password@mysql:3306/crud_db
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api:/app
    restart: unless-stopped
